### PR TITLE
Added remappings feature and improved contract template 

### PR DESCRIPTION
**Pull request by skrafft**

### CODE REVIEW

**Comment by frangio** [comment]
Thanks for contributing @skrafft! This PR includes two independent things. Let's discuss them separately.

#### Remappings

This is related to #24, but is not an ideal solution because the remappings need to be specified manually. I'd want us to use something like [resolver-engine](https://github.com/Crypto-Punkers/resolver-engine) that is able to automatically build the remappings. What do you think about this approach?

#### Linebreaks

I'm not sure I understand the reason for this change. Would you mind explaining why you introduced this?

**Comment by skrafft** [comment]
Hi @frangio,

For the remappings, using resolver-engine seems like a good idea. I'll try to find time to go this way.
For the linebreaks, I noticed that writing this kind of code for documentation:

```
@dev Line 1 with text
@dev Line 2 with another text
```

leads to the following documentation:

```Line 1 with text Line 2 with another text```

This is not very readable and I thought that it would be better with a line break:

```
Line 1 with text
Line 2 with another text
```

**Comment by frangio** [comment]
The natspec

```
@dev Line 1 with text
@dev Line 2 with another text
```

would result in output

```
Line 1 with text
Line 2 with another text
```

The issue is that Markdown concatenates the two consecutive lines. You should make sure to include an extra newline in your natspec:

```
@dev Line 1 with text

@dev Line 2 with another text
```

**Comment by skrafft** [comment]
Your solution works but then the natspec is a bit dirty with blank lines. Especially if everything is documented through natspec as it is in our case.

**Comment by frangio** [comment]
With blank lines, definitely, but if you use the asterisk prefix in every line it looks quite neat IMO. Take a look at the OpenZeppelin source code.

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/54ee1c7ff59462bc300c0dc96cb71eb1e3cbdb45/contracts/token/ERC20/ERC20.sol#L7-L20

What do you think?

**Comment by skrafft** [comment]
It's not that bad. I didn't notice that you did not need the @dev keyword multiple times (which was what I wrote and clearly makes the comment unreadable.

**Comment by frangio** [comment]
The remappings feature may be superceded by the more general #45.

**Comment by frangio** [comment]
Now that #45 is merged remappings are supported.

**Pull request closed without merging**
