### PR TITLE
Increased max buffer size given to solc

### LINKED ISSUE #12: Error: Command line operation failed with code 1.
I am trying to generate the docs using the solidity-docgen. Earlier it was working fine but suddenly it is behaving very weird.
getting this error 

> Error: Command line operation failed with code 1.
 at handleErrorCode (/usr/local/lib/node_modules/solidity-docgen/lib/index.js:133:11)
    at parseProject (/usr/local/lib/node_modules/solidity-docgen/lib/index.js:123:3)
    at exports.default (/usr/local/lib/node_modules/solidity-docgen/lib/index.js:20:23)
    at Command.program.version.arguments.option.action (/usr/local/lib/node_modules/solidity-docgen/bin/solidity-docgen:32:5)
    at Command.listener (/usr/local/lib/node_modules/solidity-docgen/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:180:13)
    at Command.parseArgs (/usr/local/lib/node_modules/solidity-docgen/node_modules/commander/index.js:653:12)
    at Command.parse (/usr/local/lib/node_modules/solidity-docgen/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/solidity-docgen/bin/solidity-docgen:44:9)
    at Module._compile (internal/modules/cjs/loader.js:654:30)

### PR DESCRIPTION
**Pull request by maxsam4**
Fixed #12 

**About the Issue**
solc spits out the output to stdout by default.
shell.js uses node's child process that has a limit of 200KB by default on the stdout buffer which is too small.
For example, size of output generated by solc for our contracts with all the flags used here is ~31MB and as a result, doc generation was failing.

**Solution**
This PR increases max buffer size to 100MB. As this is the max size and it will not be reserved by default, this PR is safe to merge. I have conservatively set it 100MB to detect any future memory leaks. This can be increased in future if need be.

### CODE REVIEW

**Comment by ealmansi** [comment]
LGTM

**Comment by maxsam4** [comment]
@frangio @spalladino can this be merged, please?

**Comment by frangio** [comment]
@maxsam4 Apologies for the delay on this. We're working on a new version of `solidity-docgen` that will not have this problem because it uses solcjs. It should be released in the next month, so I would prefer to focus on that and not merge this.

Is this affecting your setup currently? Or would waiting a couple more weeks work for you?

**Comment by maxsam4** [comment]
> Is this affecting your setup currently? Or would waiting a couple more weeks work for you?

I am using my fork of solidity-docgen to generate docs as it's unusable for us without this fix. I just want to move back to using official version instead of my own fork. As this fix does not break anything, I see no reason for this to not be part of the official version. I can keep using my own fork if you don't want to merge this simple fix.

Re. solcjs
Please keep it optional. Native solc is much faster than solcjs and has fewer bugs. 
solcjs stops working after the source code size increases to ~1.3 MB. https://github.com/ethereum/solc-js/issues/330

Our source code is currently 887KB + a few KB for OZ contracts on top of that. We might soon be unable to use solcjs for anything in our project. We are currently using native solc for everything and it's much better dev experience once you get it set up :). On mac, on linux and windows and rpi, on everything :).

**Comment by frangio** [comment]
Thank you for bringing this up @maxsam4. As mentioned before we have rewritten the tool and it is using solcjs for now. But keeping in mind what you said, I've opened #25 to add native solc as an option.

**Pull request closed without merging**
